# Generated by Django 3.1.1 on 2020-09-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200907_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='seen_by',
            field=models.CharField(default='', max_length=64),
        ),
    ]
